### ISSUE TITLE
Doesn't allow passing cli options to pkg

### ISSUE THREAD

**Issue by lukebarton** [fmiras/next-pkg#72] opened 2019-05-25 18:11 UTC
I want to target another platform that's not `host`.

```
const execution = exec([
      finalServerPath,
      '--target',
      'host',
      '--output',
      `${binaryFilePath}`
    ])
```

**Comment by fmiras** [comment] 2019-05-27 21:30
duplicate of #3

**Closed as completed by fmiras** 2019-05-27 21:30 UTC
